### ISSUE TITLE
✅ FEATURE: 혜택 페이지 구현

### ISSUE THREAD

**Issue by nhyeonii** [GDG-24-25-KAKAOBANK-Android/GDG-Team2#10]
# 📝 Description
혜택 페이지 구현 

## 📌 Todo
- [x] 페이지 배너 구현
- [x] LazyRow 기능 사용
- [x] 좋아요 버튼 기능 활성화
